### ISSUE TITLE
Update usage instructions to remove Java setup

### ISSUE THREAD

**Issue by schivmeister** [foooomio/setup-jena#9]
Currently the README instructions mention the following:

```
  - uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17 # Jena4 requires Java 11+
```

This setup for Java is redundant and therefore not required as the Ubuntu runners come with Java by default. See https://github.com/actions/runner-images/issues/9848 (default changed from 11 to 17 from 22.04 to 24.04) and https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md (it appears even 20.04 had 11 as default).

Thanks for this maintaining this Action!
